import { test, expect, chromium } from '@playwright/test';

// Define the list of domains you want to check
const domainsToCheck: string[] = [
    'slotsmobile.co.uk', 'slotsmobile.com', 'slotsninja.com', 'slotsnsports.com',
    'slotsofvegas.com', 'slotsons.com', 'slotspalace.com', 'slotsroom.com',
    'slotstars.com', 'slotster.com', 'slotstoto.com', 'slotsuk.co.uk',
    'slotswincasino.com', 'slotszone.com', 'slott.com', 'slott.club',
    'slotter.casino', 'slotti.com', 'slottica5.com', 'slottio.com',
    'slotto.co.uk', 'slottojam11.com', 'slottyslots.com', 'slottyvegas.co.uk',
    'slottyvegas.com', 'slottyvegas.eu', 'slottyway.com', 'slotum.com',
    'slotuna3.com', 'slotv.ro', 'slotwhales.com', 'slotwolf.com',
    'slotystake.com', 'slotzilla.co.uk', 'slotzo.com', 'smarkets.com',
    'smartmobilecasino.co.uk', 'smartbahis169.com', 'smashingcasino.com',
    'smashup.com', 'smilebet24.it', 'smokace.com', 'smoochbingo.co.uk',
    'smoothbingo.co.uk', 'smoothspins.co.uk', 'snabbare.com', 'snabbis.com',
    'snai.it', 'snappybingo.com', 'snatchcasino.com', 'snatchcasino12.com',
    'snatchcasino2.com', 'snowybingo.com', 'sobingo.co.uk', 'soccabet.com',
    'soccerbet22.it', 'socialgame24.it', 'sodovn1.com', 's99902a.com',
    'sodo102.com', 'sofabet365.it', 'sofortlos.de', 'casino-pp.net',
    'sohocasino.com', 'sokabet.co.tz', 'sol.casino', 'solcasino.es',
    'solarspins.com', 'solwin77.com', 'solbet.pe', 'solcasino.io',
    'solisbet.com', 'casinosolverde.pt', 'solverde.pt', 'somanyslots.com',
    'somoscasino.com', 'sonnenspiele.de', 'sons-of-slots.com',
    'sonsofslots.com', 'sorare.com', 'southbeachbingo.ag',
    'southerncrossbet.com.au', 'spacecasino.co.uk', 'spacefortuna.com',
    'spacelilly.com', 'spacewins.com', 'spacebet.eu', 'spacewincasino.com',
    'spadesqueen.com', 'sparkleslots.com', 'sparklingbingo.com',
    'sparklybingo.com', 'spartanpoker.com', 'spartanslots.com',
    'spassino.com', 'spectrabingo.com', 'speedbet.com', 'speedycasino.com',
    'speedyslot.com', 'speedybet.com', 'speedyspel.se', 'spela.com',
    'spelet.lv', 'spelklubben.se', 'spicebingo.co.uk', 'spicyspins.com',
    'spicyjackpots.com', 'spiderslots.com', 'spildansknu.dk',
    'spilleboden.dk', 'spillehallen.dk', 'spilleren.com', 'spilnu.dk',
    'spinandwin.com', 'spincasino.com', 'spinpalace.com', 'spinpalace.org',
    'spinpalacecasino.net', 'spinpalaceonlinecasino.com',
    'spindimension.com', 'spindinero.com', 'spindinerocampaign.com',
    'spinfever.com', 'spinfiesta.com', 'spingalaxy.com', 'spingenie.ca',
    'spingenie.com', 'spinhill.com', 'spinjackpots.com', 'spinlovers.com',
    'spinmadness.com', 'spinmillion.com', 'spinoasismails.com',
    'spinpalace.it', 'spinprincess.com', 'spinpug.com', 'spinrider.com',
    'spinsamba.com', 'spinsamurai.com', 'spinshake.com', 'spinsports.com',
    'spinstation.com', 'spinstralia.com', 'spin.bet', 'spin.city',
    'spincity-plays.com', 'spin.ro', 'spin247.com', 'spin996.com',
    'spinago.com', 'spinago3.casino', 'spinamba.com', 'spinanga.fr',
    'spinanga5.com', 'spinarium1.com', 'spinaro.com', 'spinaru.com',
    'spinatra.mobi', 'spinaway.ca', 'spinaway.com', 'spinbet.com',
    'spinbetter.com', 'spinbit.com', 'spinbookie.com', 'spinbounty.com',
    'spinch.com', 'spinero.com', 'spinfest.com', 'spinfields.com',
    'spinfinity.casino', 'spinia.com', 'spinight3.com', 'spinit.com',
    'spinjo.com', 'spinjuju.com', 'spinland.com', 'homelander777.com',
    'spinlander.com', 'spinlander1.com', 'spinlander3.com',
    'spinline.com', 'spinmywin.com', 'spinnalot.com', 'spinni.com',
    'spinoli1.com', 'spinoloco2133.com', 'spinoverse.com', 'spinpirate.com',
    'spinrio.com', 'spinrollz3.com', 'spinscruise.com', 'spinsgods.com',
    'spinsroyale.com', 'spins.lv', 'spinsbro.com', 'spinsino.com',
    'spinslots.com', 'spinson.com', 'spinspace.io', 'spinspirit1.net',
    'spinstar.bet', 'spinsup.com', 'spinsy.com', 'spintasticcasino.com',
    'spintime.io', 'spintropolis.com', 'spinupcasino.club', 'spinurai.com',
    'myspinwins.com', 'spinwinslots.co.uk', 'spinybet.com', 'spinyoo.com',
    'spinz.com', 'spinzaar.com', 'spinzilla.com', 'spinzwin.com',
    'spiritcasino.com', 'splitacescasino.com', 'sponsiobet.com',
    'sportandgames.it', 'sportaza.com', 'sportbet.com', 'sportbet.one',
    'sportbet.it', 'sportbet3.it', 'sportbet365.it', 'sportbull.it',
    'sportcash.net', 'sportchamps.com.au', 'sportempire.com',
    'sportimba.com', 'sportingbet-br.ne', 'sportingbet.co.za',
    'sportingbet.com', 'sportingbet.gr', 'sportingbet.ro',
    'sportingbet.tv', 'sportingbet412.com', 'sportingbet812.com',
    'sportingbull425.com', 'sportingindex.com', 'sportitaliabet.it',
    'sportito.com', 'sportium.es', 'sportiumbet24.it',
    'sportnation.bet', 'sportpesa.co.tz', 'sportpesa.co.za',
    'sportpesa.com', 'sportpesa.it', 'sportpesa.uk',
    'sportpesagoals.com', 'sportsbetting.ag', 'sportsinteraction.com',
    'sports-gambling.com', 'sportsbet.co.za', 'sportsbet.com',
    'sportsbet.com.au', 'sportsbet.io', 'sportsbetio.uk',
    'sportsbetting.com', 'sportsbetting.com.au', 'sportsbettingonline.ag',
    'sportsbook.ag', 'sportsbook.com', 'sportsbroker.com',
    'getsporttrade.com', 'sportuna1.com', 'sportwetten.de',
    'sportybet.com', 'spotgaming.com', 'bahissikayetleri.org',
    'spotonbets.co.za', 'spreadex.com', 'spreads.ca', 'spree.com',
    'springbokcasino.co.za', 'sprutcasino.com', 'spudo.com',
    'spybingo.com', 'spyslots.com', 'spybet.com', 'spybet2.com',
    'srslots.com', 'ssbet77.net', 'stake.games', 'stake.us',
    'stake1021.com', 'stake7.com', 'stakebro.com', 'stakemania.com',
    'stakemate.com', 'stakeprix.com', 'stakes.com', 'stakewin.io',
    'stakezon.com', 'unibet.co.uk', 'stanleybet.it', 'stanleybet.ro',
    'stanleygames.be', 'starbet.rs', 'starcasino.be', 'starslots.com',
    'starslots.ie', 'starspinners.com', 'starsports.bet',
    'starspreads.com', 'starvegas.it', 'starwins.co.uk',
    'star-casino.cz', 'starbet.co.ke', 'starbet33.com', 'starbets.io',
    'starcasino.it', 'starcasinodice.be', 'starda.casino',
    'stardice.be', 'stardustcasino.com', 'stargame.it',
    'service-mainfranken.de', 'stargames-alternative.de',
    'stargames-bonus.com', 'stargames-online.com', 'stargames.com',
    'stargames.de', 'stargazebingo.com', 'starmatch.it',
    'starplayup.it', 'starsdraft.com', 'starspins.com',
    'starvegas.es', 'starvegas.ch', 'starwin.it', 'staryes.it',
    'starzino.com', 'staxino.com', 'staycasino.com',
    'mktstaylucky.com', 'staybet.com', 'stelario.com',
    'stellabingo.com', 'stellarspins.com', 'stereospins.com',
    'stickpoolclub.com', 'stickyslots.com', 'stoiximan.gr',
    'stonebahis130.com', 'stonevegas3.com', 'storspelare.se',
    'storspiller.com', 'streambet.io', 'streambetz.com',
    'strendus.com.mx', 'strictlycash.co.uk', 'strikeitalia.it',
    'sts.pl', 'stsbet.co.uk', 'stsbet.com', 'stupidcasino.com',
    'suertia.es', 'sugarbingo.com', 'sugarcasino.com',
    'playsugarhouse.com', 'sugarspins.com', 'sultanbet.com',
    'summitcasino.com', 'sunpalacecasino.com', 'sunpalacecasino.eu',
    'thesunvegas.co.uk', 'sunbet.co.za', 'sunbet.com.gh',
    'sundaebingo.com', 'sunmaker.com', 'sunmaker.de',
    'sunmakercasino.de', 'sunnywins.com', 'sunnycasino.com',
    'sunnyplayer.com', 'sunpura.com', 'sunriseslots.com',
    'sunsetcasino.com', 'sunsetspins.com', 'sunubet.com',
    'suomiarvat.com', 'suomiautomaatti.com', 'suomikasino.com',
    'suomivegas.com', 'supabets.co.za', 'supabets.com.gh',
    'supacasi.com', 'superboss.com', 'supercasino.com',
    'supercasino.fr', 'superfortunes.com',
    'supermegafluffyrainbowvegasjackpotcasino.com', 'superslots.ag',
    'super10bet87.com', 'skysports.com', 'superace88.com',
    'superaposta.top', 'superb.bet', 'bahis.casino', 'superbet.gy',
    'superbet.br', 'superbet.ro', 'superbook.com', 'supercasino.ee',
    '1supercatcasino.com', 'superdraft.io', 'supergame.be',
    'supergaminator.com', 'superiorcasino.com', 'superiorcasino.eu',
    'superkasino.com', 'superlottoclub.com', 'supernopea.com',
    'supernovacasino.com', 'supernovanew.com', 'superplay.mx',
    'supersnabbt.se', 'supersport.hr', 'supertotobet809.com',
    'superwin.com', 'casinosuperwins.com', 'suprabets.com',
    'supraplay.com', 'supremeplay.com', 'supremo.com',
    'sure2.win', 'surebet247.com', 'surfcasino.com', 'surfplay.com',
    'surge.com.au', 'sushicasino.com', 'sutbet325.com', 'sv88.win',
    'svedalacasino.com', 'sven-play.com', 'svenbet.com',
    'svenskaspel.se', 'sverigekronan.com', 'sverigelotten.se',
    'swagbingo.com', 'swankybingo.com', 'swcpoker.club',
    'sweepslots.com', 'sweetshopbingo.com', 'sweetwins.com',
    'sweetywin.com', 'swerte99.news', 'swerteplay.com.ph',
    'swiftcasino.com', 'swiftspiele.de', 'swiftbet.com.au',
    'swiftygaming.com', 'swiper4.com', 'swishbetcasino.com',
    'swiss4win.ch', 'swisscasinos.ch', 'swisslos.ch', 'swopstakes.com',
    'sxvegas.com', 'sykaaabw.com', 'sykaaa.com', 'syndicate.casino',
    'synottip.cz', 'synottip.lv', 'synottip.sk', 'synottippoker.cz',
    'szerencsejatek.hu', 'trexbingo.com', 't1bet.be', 't7myr.com',
    'ta88.com', 'tab.com.au', 'tabackbet.it', 'tabgold.co.za',
    'tabonline.co.za', 'tabtouch.com.au', 'tabtouch.mobi',
    'tahiticasino.com', 'taikaspins.com', 'takeabreakbingo.co.uk',
    'takemeoutgames.com', 'takeawayslots.com', 'taksimbet51.com',
    'talismania3.com', 'talksportbet.com', 'tamambet110.com',
    'tangierscasino.com', 'tarafbet31.com', 'targetslots.com',
    'tastybingo.com', 'tbet.it', 'tdameritrade.com',
    'teapuesto.pe', 'teatimebingo.co.uk', 'tebwin.com', 'tedbingo.com',
    'tedbet.com', 'tedcasino.com', 'tehokasino.com', 'teknogame.it',
    'televega.com', 'tellygames.com', 'templenile.com', 'tempobet.com',
    'ytxt2.com', 'tennisi.bet', 'tenvegas.com', 'terrybet.it',
    'teslabahis293.com', 'tatkazino.lt', 'tether.be', 'texbet.com.au',
    'texsportbet.com', 'tf88v.com', 'tg.casino',
    'theclubhousecasino.com', 'thegoldlounge.com', 'thegreek.com',
    'healthlottery.co.uk', 'thekingbet.com', 'thelotter.com',
    'lotteryoffice.com.au', 'national-lottery.co.uk',
    'national-lottery.com', 'thepalaces.com', 'thephonecasino.com',
    'thepools.com', 'theredlioncasino.com', 'rialtocasino.com',
    'theslotsisland.com', 'sunbingo.co.uk', 'thesunplay.co.uk',
    'thevic.com', 'thexfactorgames.com', 'thebescasino.com',
    'thebettercasino.com', 'thediamond.casino', 'thelott.com',
    'thelotter.se', 'theonlinecasino.co.uk', 'thepapelbet82.com',
    'thescore.bet', 'thevirtualcasino.com', 'thisisvegas.com',
    'thorslots.com', 'thorcasino.com', 'thrills.com', 'thrillsy.com',
    'thrivefantasy.com', 'thronebet.com', 'thunderbet.com.au',
    'thunderboltcasino.com', 'thunderpick.com', 'thunderpick.io',
    'tictacbets.co.za', 'ticketybingo.com', 'tigergaming.com',
    'tigerriches.com', 'tigerspin.com', 'tikifortunes.com',
    'tikitaka3.com', 'tiktakbet.com', 'tiktokcasino.com',
    'tiltbet.it', 'timberazo.com', 'time2spin.com', 'time4bets.com',
    'timebetgirisi1.com', 'timetobet.it', 'timewin.it', 'tinbet.pe',
    'tinyslots.com', 'tiptopbingo.com', 'tipbet.com',
    'tipico-affiliates.com', 'tipico-careers.com', 'tipico-group.com',
    'tipico-usa.com', 'tipico-wettshop.com', 'tipico.at',
    'tipico.be', 'tipico.casino', 'tipico.com', 'tipico.de',
    'tipico.dk', 'tiplix.info', 'tipobet0650.com', 'tipp24.de',
    'tipp3.at', 'tippen4you.com', 'tippland.de', 'tippmixpro.hu',
    'tipsport.cz', 'tipster.de', 'tiptorro.de', 'tipwin.com',
    'tipya.com', 'titanpoker.com', 'titanbet.co.uk', 'titanbet.com',
    'titanplay.cat', 'winrivertiverton.com', 'tivit.be',
    'tivolicasino.dk', 'tlaqnacasino.com', 'tlcasino224.com',
    'tlcbet.co.uk', 'toalsbet.com', 'todoslots.es', 'tokendevils.com',
    'tokenwin.com', 'tokipot.com', 'tolbet179.com', 'tombola.co.uk',
    'tombola.es', 'tombola.it', 'tombola.nl', 'tombola.se',
    'tombolaarcade.co.uk', 'tombriches.com', 'tony99.net',
    'tonybet.com', 'tonybet.es', 'tonybetpoker.com',
    'tooniebet.com', 'topdogslots.com', 'topbet.au', 'topbet.eu',
    'topbet24.it', 'topbetta.com.au', 'topcgame.com', 'topitalia.it',
    'topkasino.com', 'topone.ph', 'topslotsite.com', 'topsport.com.au',
    'topsport.lt', 'toptally.com', 'topukcasino.com', 'topx.one',
    'tornadobet.com', 'tornadobet11.com', 'tornadobet55.net',
    'tornadobet666.com', 'tornadobet888.net', 'torocasino.com',
    'tortugacasino.com', 'toshi.bet', 'tplay.it',
    'tradacasino.com', 'tradaspiele.de', 'tradeit.gg', 'tradie.bet',
    'traditioncasino.com', 'traditioncasinos.co', 'trafonline.pl',
    'tragaperras777.es', 'trbet.com', 'treasurebingo.com',
    'treasuremile.com', 'treasurespins.com', 'trebet.it',
    'trebolplay.com', 'trendbetgiris.net', 'trendybingo.com',
    'tri88.shop', 'tri88indo.com', 'trickz.com', 'tringobet.com',
    'trinkbet120.com', 'trinocasino.com', 'trip2vip.com',
    'tripleseven.casino', 'tripscasino.com', 'triumphcasino4.com',
    'trivelabet.com', 'tropeziapalace.com', 'tropicslots.com',
    'tropicacasino.com', 'tropicalbit24.com', 'tropicanacasino.com',
    'trotto.de', 'truebluecasino.com', 'true-fortune.com',
    'truepoker.eu', 'trueflip.io', 'trueluck.com', 'truenorth.bet',
    'trustdice.win', 'truvabet.org', 'timessquarecasino.com',
    '117tsars.com', 'tsars.com', 'ttr.casino', 'tucheze.com',
    'tuckshopbingo.com', 'tulipbett.com', 'tulotero.es',
    'tulotero.mx', 'tuplaus.com', 'turbico.com', 'turbocasino.com',
    'turbovegas.com', 'turbobet87.com', 'turbonino.com',
    '376turkbet.com', 'turningstone.com', 'tuskcasino.com',
    'tutkubahis104.com', 'tuttur.com', 'tvbet.com', 'tvg.com',
    'twicedice.com', 'twin.com', 'twinriver.com',
    'twinkleslots.com', 'twinkywin.com', 'twins88.com', 'twinsbet.lt',
    'twinspires.com', 'twisterwins.com', 'twofatladies.co.uk',
    'twoupcasino.com', 'tp88.vip', 'usbank.com', 'ua.casino',
    'uabet.online', 'uberlucky.com', 'ubet.com.cy', 'uco.bet',
    'uea8a.com', 'ufa222.io', 'ufa.bot', 'ufabet.gold', 'ufabet.mobi',
    'ufabet.mom', 'ufabet3663.com', 'ufastar356.com', 'ugobet.com',
    'ukcasino-club.co.uk', 'ukcasinoclub.eu', 'uk88.top',
    'uk-bingo.net', 'ukonlineslots.com', 'ukslotgames.com',
    'ukslots.com', 'uk-wl.co.uk', 'ultimacasino.co',
    'ultraca.com', 'ultrabet346.com', 'umbingo.com', 'umiiumii.com',
    'unboxskins.com', 'ubet.co.uk', 'unibet-23.com',
    'unibet-3.com', 'unibet.be', 'unibet.ca', 'unibet.co.uk',
    'unibet.com', 'unibet.com.au', 'unibet.de', 'unibet.dk',
    'unibet.eu', 'unibet.fr', 'unibet.ie', 'unibet.it',
    'unibet.nl', 'unibet.ro', 'unibet.se', 'unibetbonus.com',
    'unibetcasino.co.uk', 'unibetcasino.com', 'unibetcommunity.com',
    'unibetmobile.co.uk', 'unibetopen.com', 'unibetsport.com',
    'uniclub.lt', 'unicorncasino.com', 'unikrn.com', 'unionsbet.it',
    'uniquecasino.com', 'unislots.com', 'univegas.it',
    'universalslots.net', 'unlimitcasino.com', 'unogg.net',
    'untoldcasino.com', 'up5zz9x.xyz', 'upcoz.com', 'upgrade.com',
    'uplayma.com', 'upoker.net', 'upswingpoker.com', 'uptownaces.eu',
    'pokiesinuptown.com', 'ursacasino.com', 'usdice.com',
    'utopiabingo.com', 'uunse.com', 'uw88india.net',
    'uwinplays.com', 'uwinsports.in', 'uwin33.org', 'v-poker.it',
    'v6bet4.com', 'v88toto3.com', 'v9bet88.net', 'va-bank9.com',
    'vaidebet.com', 'vaidebob.com', 'vale.mx', 'valsports.bet',
    'vamos.bet', 'vampirebingo.com', 'vanguardscasino.com',
    'vasycasino.com', 'vauhdikas.com', 'vauhti.com', 'vavada.com',
    'vavada26.com', 'vave.casino', 'vave.com', 'vbet.com',
    'vbet.fr', 'victorybet.ro', 'vbet88aus.com', 'vcasino.be',
    'vdcasino531.com', 'veerbet.com', 'vegabetyenigiris.com',
    'vegadream.com', 'casinovegasamped.com', 'vegas-avtomati23.com',
    'vegasberry.com', 'vegascasinoonline.eu', 'vegascountrycasino.com',
    'vegascrestcasino.ag', 'vegasdays.com', 'vegasdayscasinos.co',
    'vegasfiesta.com', 'vegashero.com', 'vegasloungecasino.com',
    'vegasluck.com', 'vegasmobilecasino.co.uk', 'vegasnowch.com',
    'vegaspalms.eu', 'vegasparadise.com', 'vegasplus.com',
    'vegasregalcasino.com', 'vegasrevenue.com', 'vegasriocasino.com',
    'vegasrushcasino.mobi', 'vegasrushcasinos.com',
    'gameassists.co.uk', 'vegasspins.com', 'vegasstripcasino.com',
    'vegaswild.com', 'vegaswins.co.uk', 'vegas.dk', 'vegas.hu',
    'vegas100.com', 'vegas2web.com', 'vegas79.app', 'vgs996.net',
    'vegascasino.com', 'vegascasino.io', 'vegascrown.com',
    'vegasino1.com', 'vegaskasino.com', 'vegaskingscasino.com',
    'vegaslandcasino.com', 'vegasmoose.com', 'vegasnight.io',
    'vegasoo.com', 'vegaswinner.com', 'vegaslegacy.com',
    'vegazcasino.com', 'vegazino.com', 'veikkaus.fi', 'velobet.com',
    'velvetbingo.com', 'velvetslots.com', 'velvetspin.com',
    'vemapostar.com', 'venetianbet.it', 'venusbetgiris.net',
    'verajohn.com', 'verajohn.se', 'veravegas.com', 'vera.casino',
    'verabet3.info', 'verdecasino.com', 'vernons.com',
    'versaillescasino.com', 'versus.es', 'versusbet.mx',
    'vertbet.com', 'verywellcasino.com', 'veslot225.com',
    'vespercasino.com', 'vevobahis672.com', 'vg66.com', 'vi68.vip',
    'vibecasino.com', 'vicsbingo.com', 'vicbet.com', 'viciwin.com',
    'vickers.bet', 'victoriamilancasino.com', 'victoriamilancasino.dk',
    'vidavegas.com', 'videoslots.city', 'videoslots.com',
    'videoslotsfun.nl', 'vie.bet', 'vierklee.com', 'v80bet.com',
    'vietbet.eu', 'viggoslots.com', 'vikibet.com', 'vikingbingo.com',
    'vikingslots.com', 'vikingbet.com.au', 'vikingbet.io',
    'vikingheim.com', 'vikingspin.com', 'viks.com', 'viktorbet117.com',
    'betvillafortuna.com', 'vinbet.com.au', 'vincipromo.it',
    'vincitubet.ke', 'vincitubet.it', 'vincosempre.it',
    'vindercasino.dk', 'vindstort.dk', 'vinnarecasino.se',
    'vinnarum.com', 'vinneri.com', 'vinylcasino3.com',
    'violetcasino.com', 'viparabclub1.com', 'vipbet.com',
    'vipclubplayer.com', 'vippowerlounge.com', 'viproomcasino.com',
    'vipslots.com', 'vipslots.eu', 'vipspel.com', 'vipspins.com',
    'vipsports.bet', 'vipstakes.com', 'vip-ibc.com',
    'vipbettingservices.com.au', 'vipcasino.com', 'vipcasino.hu',
    'vipclub.casino', 'vipcoincasino.com', 'viperspin.com',
    'viperwin3.com', 'vipgame.io', 'vippark143.com', 'vipscasino.com',
    'vipslot.club', 'vipsports.eu', 'virgincasino.com',
    'virgingames.com', 'valottery.com', 'virtualcitycasino.com',
    'vistabet.gr', 'vitalbet.com', 'vitoace.com', 'vivafortunes.com',
    'vivabet.it', 'vivabet.ro', 'vivadice.com', 'vivagol.com',
    'vivatbet.ee', 'vivemoncasino.com', 'vivobet.com',
    'vizebet103.com', 'vizyonbet337.com', 'vladcazino.ro',
    'vloot.io', 'vnn138.com', 'vn88.app', 'vntop88.com',
    'vnebet.it', 'vnloto.vip', 'vodds.net', 'vodka.bet',
    'vogliadivincere.it', 'volcanicslots.com', 'volcanobet.ba',
    'volcanobingo.co.uk', 'volcanovegasclub.net',
    'volcanobet.com.au', 'volltreffer.com', 'volna.casino',
    'voltcasino.com', 'voltacasino.com', 'voltslot.com',
    'voodoo.casino', 'voodoowins.com', 'voodoodreams.com',
    'voozaza.com', 'vortexcasino.com', 'vplay.it',
    'vstarbet.com', 'vstart.it', 'vtbet88.com', 'delyxx-vull7.com',
    'maximumvulkan2.com', 'vulkanplatinum.com', 'vulkanroyalcazino.com',
    'vulkan-royal1.pro', 'vulkanrussia.com', 'vulkanstavka.com',
    'vulcanvegas.com', 'vulkanvegas.com', 'vulkan24club.com',
    'vulkan777.com', 'vulkanbet.com', 'vulkanspiele.com',
    'w1n-vstars.com', 'vuoiscommettere.it', 'vwin030.com',
    'vx88.com', 'vz684.com', 'wcasino-online.net', 'w138.com',
    'w388.com', 'w-69.mobi', 'w88.com', 'wacko.ro',
    'wagerbeat312.com', 'wagerweb.eu', 'wagmicasino.io',
    'wagonbet.com', 'walebet.com', 'wallacebet.com', 'wanabet.es',
    'wanejobets.co.za', 'wantedwin.com', 'warriorwins.com',
    'wasino.com', 'watchmyspin.com', 'watchandwager.com',
    'wazamba.com', 'wazbee.casino', 'wazo-bet.com', 'wazobet.com',
    'wbahis106.com', 'mywbet.com', 'wbetz.com', 'wclub365.com',
    'wewantbingo.com', 'we88myr.com', 'web.de', 'webbyslot.com',
    'webetnet.com', 'wefabet.com', 'weiss.bet', 'welcomebingo.com',
    'welcomeslots.com', 'welldoneslots.com', 'wellbet.com',
    'welle.casino', 'wellington-casino.be', 'weltbet.com',
    'weplayers.it', 'westcasino.com', 'westgateresorts.com',
    'westlotto.de', 'westpointcasino.com', 'wettarena.de',
    'wettenlive.com', 'wettigo.com', 'wettmeister.com',
    'wettstar-pferdewetten.de', 'wg.casino', 'whamoo.com',
    'wheeloffortunecasino.com', 'wheelingisland.com', 'wheelz.com',
    'wheelzgames.de', 'whirlwindslots.com', 'whitelionbets.com',
    'whitelioncasino.com', 'whitelotuscasino.com',
    'wickedjackpots.com', 'wickedbet.com', 'wikibet.com',
    'wikiluck.com', 'wikiwins.com', 'wildbetsentertainment.com',
    'wildcardcasino.com', 'wildcardcity.com', 'wilddicecasino.com',
    'wildfortune.com', 'wildjackcasino.com', 'wildjackpots.com',
    'wildjunglecasino.com', 'wildspinner.com', 'wildsultan.com',
    'wildtokyo.com', 'wildtokyo22.com', 'wildtokyo23.com',
    'wildtokyo777.com', 'wildtornado.casino', 'wildvegascasino.com',
    'wildwestwins.com', 'wildwildcasino.io', 'wildwins.com',
    'wild.io', 'wild24.co.uk', 'wild7.bet', 'wildblaster.com',
    'wildcasino.ag', 'wildcasino.us', 'wildcoins.io',
    'wilderino.com', 'wildfortune.io', 'wildpharao.com',
    'wildrobin1.com', 'wildsino1.com', 'wildslots.com', 'wildz.com',
    'wildz.de', 'willscasino.com', 'willbet.ai', 'williamhill.com',
    'williamhill.es', 'willycasino.dk', 'wilsonbet.com',
    'casinowinaday.com', 'winadaycasino.eu', 'winbritish.com',
    'windiggers.com', 'winitbingo.com', 'winmonac.com',
    'winpalace-casino.com', 'winparadise.com', 'wintrillions.com',
    'winwindsor.com', 'win2.ro', 'win2day.at', 'winabet365.com',
    'winamax.fr', 'winawin.com', 'winbay.com', 'winbay3.com',
    '33winbet.com', '55winbet.com', 'newwinbet.com', 'topwinbet.com',
    'uwinbets.com', 'uwinbets.ug', 'winbet-bg.com', 'winbet.bg',
    'winbet.it', 'winbet.ro', 'winbet.us', 'winbet.website',
    'winbet555.com', 'winbetaffiliates.bg', 'winbetgroup.ro',
    'winbet365.it', 'winbig21.com', 'winbir358.com', 'winboss.ro',
    'winbrokes.com', 'wincasino.it', 'winchile.com', 'win.city',
    'windcreekcasino.com', 'windaddy.com', 'windetta.com',
    'windfallcasino.co.uk', 'windice.io', 'winfest.com',
    'winfest.de', 'winsportbet.com', 'wingaga3.com',
    'winhalla.com', 'winhub.it', 'winissimo.com', 'winkbingo.com',
    'winkslots.com', 'wink.org', 'winka.it', 'winkbet.it',
    'winlandia.com', 'winlegends1.com', 'winline.ru',
    'winmaker.com', 'winmasters.com', 'winmasters.com.cy',
    'winmasters.gr', 'winmasterspokeropen.com', 'winmax.it',
    'winmega.com', 'winmi.com', 'toto.nl', 'winner.bet',
    'winner.com', 'winner.ro', 'winnerama.com', 'winnercasino.bet',
    'winnermillion.com', 'winneroo.com', 'winnersclub.com',
    'winnersmagic.com', 'winners.bet', 'winnersbet.com.au',
    'g2afse.com', 'winnerz.com', 'winnerzon.com',
    'winningdays.com', 'winningkings.com', 'winninglucky.com',
    'winning.io', 'winningft.com', 'winningroom.com',
    'winnings.com', 'winningz.com', 'winningz5.com',
    'winnita.com', 'winny.com', 'winolla.com', 'winolot1.com',
    'winomania.co.uk', 'winorama.com', 'winorio.com',
    'winota.com', 'winoui.com', 'winown.com', 'winportcasino.com',
    'winpot.mx', 'wins88.com', 'winspark.com', 'winsroyal.com',
    'winsane.com', 'winshark.com', 'winsly.com', 'winsmania.com',
    'winspinbet.com', 'winspirit.com', 'winstark.io',
    'winstler.com', 'winstonbet.com', 'winstoria.com',
    'winstroria.com', 'wintika.com', 'wintimecasino.it',
    'wintingo.com', 'wintokens.io', 'wintomato.com',
    'wintopia.com', 'wintoto.it', 'winuniquecasino.com',
    'winviewgames.com', 'winwardcasino.com', 'winwin-bet.com',
    'winwin.bet', 'winxbet.net', 'winz.io', 'winzie.com',
    'winzinator.com', 'winzino.com', 'winzir.ph', 'winzon.com',
    'winzz.com', 'wipbet491.com', 'wirwetten.com',
    'wiracasino.com', 'wishbingo.com', 'wishbet.com.au',
    'wishcasino.io', 'wisho.com', 'wixstars.com', 'wizslots.com',
    'wizardslots.com', 'wizary.com', 'wizbet.com',
    'wizebets.com', 'wizzspin.com', 'wolbet154.com',
    'wolfspins.com', 'wolfwinner.com', 'wolfwinner.online',
    'wolf.bet', 'wolfycasino.com', 'womanbingo.com',
    'womansown-bingo.co.uk', 'wombatcasino.com', 'wombet.com',
    'wonaco.com', 'wonaco3.com', 'wonclub.com',
    'casino-wonder.com', 'wongagames.co.uk', 'wonodd74.com',
    'wonodd98.com', 'woocasino.com', 'woocasino1.com',
    'woollybingo.com', 'woopio.com', 'woopwin.com',
    'worldsportsbetting.co.za', 'worldwinner.com',
    'wowbingo.co.uk', 'wowcasino.com', 'wowlotto.ng',
    'wowvegas.com', 'wow888.fun', 'wowcherbingo.com',
    'wplay.co', 'wpokies.com', 'wptglobal.com', 'wptglobal.mx',
    'wshful.com', 'wsmcasino.com', 'playwsop.com', 'wsop.ca',
    'wsop.com', 'wtfskins.com', 'wtgbingo.com', 'wunderino.com',
    'wunderino.de', 'wunderwins.com', 'wwin.com', 'wy88bet.com',
    'wynnbet.com', 'x-bet.co', 'x1casino.com', 'x3000.com',
    'x3000.eu', 'x7casino.com', 'xbet.ag', 'xcasino.com',
    'xipcasino.com', 'xlcasino.com', 'xlbet.com', 'xlivebet.com',
    'xo88.win', 'xon.bet', 'xotto.de', 'xparibet.com',
    'xplaybet.com', 'xpokies.com', 'xsino.io', 'xslot45.com',
    'xtip.de', 'xtremewin.co.uk', 'yapoker.com',
    'ya888ya-casino.com', 'yaacasino.com', 'yaasscasino.es',
    'yabbycasino.com', 'yajuego.co', 'yakabet145.com',
    'yakocasino.com', 'yallabet30.com', 'yamabet.net',
    'yangasport.com', 'yas.be', 'yaybingo.com',
    'ybetfr.com', 'ybet.com', 'inmerion.com', 'ybets.net',
    'yebet.com', 'yebocasino.co.za', 'yeeehaaa.be', 'yekbet.com',
    'yellowbet.com', 'yesbingo.co.uk', 'yesbet88.online',
    'yesplay.be', 'yeticasino.com', 'yetiwin.com', 'yocasino.es',
    'yoapuesto.mx', 'yobetit.com', 'yobingo.es', 'yodabet172.com',
    'yohooslots.com', 'yojicasino.ro', 'yoju.casino',
    'yolocasino.com', 'yonibet.com', 'yorkbet174.com',
    'yosports.es', 'youcasinobet.com', 'youspinyouwin.com',
    'youbet.it', 'youbetcha.com', 'youplayweplay.com',
    'yourbet.com', 'yourfavoritecasino.com', 'yourwin24.com',
    'yous777.com', 'youslots.it', 'youwager.lv', 'youwin.com',
    'yoyocasino.com', 'yoyocasino.se', 'yugibet.com',
    'yukongoldcasino.co.uk', 'yukongoldcasino.eu',
    'yummywins.com', 'yuugado.com', 'yyycasinoonline.com',
    'yyyonline5.com', 'zamba.co', 'zanzibet.com',
    'zarcasino.co.za', 'zaza.com', 'zbetvn.com',
    'zebet.com', 'zebet.fr', 'zebrawins.com',
    'zenbetting.com', 'zenspin.com', 'zenbahis181.com',
    'zen.be', 'zencasino.com', 'zencasino888.com',
    'zensports.com', 'zeoncasino57.com', 'zep.be',
    'zeslots.com', 'zetcasino.com', 'zetcasino1.com',
    'zetbet.com', 'zeturf.be', 'zeturf.fr', 'zeusbingo.com',
    'zeuswin.com', 'zevcasino.com', 'zigzag777.com',
    'zigzagsport.com', 'zingabet11.com', 'zingerbingo.com',
    'zingerspins.com', 'zingobingo.com', 'zinkra.com',
    'zinocasino.com', 'zipangcasino.com', 'zipcasino.com',
    'zirkabet.com', 'zixcasino.com', 'zodiacbet.com',
    'zodiac.casino', 'zodiaccasino.com', 'zodiacu.com',
    'zoesbingo.com', 'zolobet.com', 'zolotoloto.com',
    'zolotoyarbuz.casino', 'zonagioco.it', 'zooma3.casino',
    'zoome.casino', 'zorgo.games', 'zorobet.com',
    'zotabet.com', 'zplay.it', 'zulabet.com',
    'zulucasino.com', 'zumospin.com', 'zweeler.com',
    'zynga.com'
];

test.describe('Domain Status Checker', () => {
    let workingDomains: string[] = [];
    let notWorkingDomains: { domain: string, error: string }[] = [];
    let redirectedDomains: { domain: string, redirectedTo: string }[] = [];

    test.beforeEach(() => {
        // Clear arrays before each test run if running multiple tests in a suite
        workingDomains = [];
        notWorkingDomains = [];
        redirectedDomains = [];
    });

    test('Check all specified domains', async ({ page }) => {
        for (const domain of domainsToCheck) {
            console.log(`Checking domain: ${domain}`);
            try {
                // Prepend 'https://' if it's missing to ensure valid URL for page.goto
                const fullUrl = domain.startsWith('http://') || domain.startsWith('https://') ? domain : `https://${domain}`;
                const response = await page.goto(fullUrl, { waitUntil: 'load', timeout: 30000 }); // 30-second timeout

                if (response) {
                    const statusCode = response.status();
                    const initialUrl = response.request().url();
                    const finalUrl = page.url();

                    if (statusCode >= 200 && statusCode < 300) {
                        if (initialUrl !== finalUrl) {
                            console.log(`  Redirected (200-299): ${domain} -> ${finalUrl}`);
                            redirectedDomains.push({ domain, redirectedTo: finalUrl });
                        } else {
                            console.log(`  Working (200-299): ${domain}`);
                            workingDomains.push(domain);
                        }
                    } else if (statusCode >= 300 && statusCode < 400) {
                        console.log(`  Redirected (${statusCode}): ${domain} -> ${finalUrl}`);
                        redirectedDomains.push({ domain, redirectedTo: finalUrl });
                    } else {
                        console.log(`  Not Working (Status: ${statusCode}): ${domain}`);
                        notWorkingDomains.push({ domain, error: `HTTP Status: ${statusCode}` });
                    }
                } else {
                    // This case might be hit if goto fails before a response is received (e.g., DNS error)
                    console.log(`  No response received for: ${domain}`);
                    notWorkingDomains.push({ domain, error: 'No HTTP response received (e.g., DNS error, network issue).' });
                }
            } catch (error: any) {
                console.log(`  Error checking ${domain}: ${error.message}`);
                notWorkingDomains.push({ domain, error: error.message });
            }
            // Add a small delay to avoid overwhelming servers and for better logging readability
            await page.waitForTimeout(200); // Reduced delay slightly
        }

        console.log('\n--- Domain Check Results ---');
        console.log('Domains returning 200s (or 2xx with no redirect):');
        workingDomains.forEach(d => console.log(`- ${d}`));

        console.log('\nDomains that redirected:');
        redirectedDomains.forEach(d => console.log(`- ${d.domain} -> ${d.redirectedTo}`));

        console.log('\nDomains not working (or other errors):');
        notWorkingDomains.forEach(d => console.log(`- ${d.domain} (Error: ${d.error})`));

        // Optional: Add assertions to fail the test if certain conditions are not met
        // For example, if you expect a certain number of domains to be working.
        // expect(workingDomains.length).toBeGreaterThan(0);
    });
});